import type { Metadata } from 'next'
import './globals.css'
import { ReactNode } from 'react'
import Auth0Wrapper from '@/app/_components/auth0-wrapper'

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type RootLayoutProp = Readonly<{
  children?: ReactNode
}>

function RootLayout(prop: RootLayoutProp) {
  return (
    <html lang='en'>
      <body>
        <Auth0Wrapper>{prop.children}</Auth0Wrapper>
      </body>
    </html>
  )
}

export default RootLayout
export { metadata }